# fly.toml app configuration file generated for apigear-hub on 2023-10-06T12:32:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pbsaas"
primary_region = "ams"

[build]
  build-target = "app"

[mounts]
  destination = "/app/pb_data"
  source = "pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024


[env]
  VITE_PB_URL = "https://pbsaas.fly.dev:8090"

