version: '3'

tasks:
  default:
    cmds:
      - task: build

  init:
    dir: app
    cmds:
      - go mod tidy
      - go mod download
      - go generate ./...

  build:
    cmds:
      - go build -o pbsaas ./app
    
  ci:
    cmds:
      - task: init      
      - task: build

  lint:
    deps:
      - app-lint

  app-lint:
    dir: app
    cmds:
      - golangci-lint run
  run:
    cmds:
      - go run ./app

  clean:
    cmds:
      - rm -rf pbsaas

  fly-deploy:
    cmds:
      - fly deploy --remote-only

  dev:
    cmds:
      - goreman start
